nome = input('Qual seu nome!?'  )
print('Bem Vindo')
e_mail = input('Digite seu e-mail!')
senha = input('Digite Sua Senha! ')
print('OK')
print(f'{nome}')
altura = float(input('Qual Sua Altura'))
print(f'{altura}')
peso = float(input('Qual seu Peso'))
imc = peso / (altura ** 2)
print(f'{imc}')